
services:
  db:
    image: mysql:8.0
    container_name: fidus_db
    environment:
      MYSQL_DATABASE: ub_wellness_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: fidus_app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ub_wellness_db
    ports:
      - "3000:3000"
    depends_on:
      - db
